from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
# from .views import hx, user_login
urlpatterns = [
    path("", views.user_login, name='login'),
    path("dashboard/", views.view_dashboard, name='view_dashboard'),
    path("ai/", views.view_aiassistant, name='view_aiassistant'),
    path("ai/query/", views.ai_assistant_query, name="ai_assistant_query"),
    path("employer/", views.view_employer, name='view_employer'),
    path("employer/<int:employer_id>/get/", views.get_employer, name='get_employer'),
    path("employer/<int:employer_id>/delete/", views.delete_employer, name='delete_employer'),
    path("logout/", views.user_logout, name='logout'),
    path("loyalty/", views.view_loyalty, name='view_loyalty'),
    path("loyalty/add/", views.add_loyalty, name='add_loyalty'),
    path("loyalty/<int:loyalty_id>/delete/", views.delete_loyalty, name='delete_loyalty'),
    path("loyalty/<int:loyalty_id>/get/", views.get_loyalty, name='get_loyalty'),
    path("loyalty/<int:loyalty_id>/history/", views.get_history_client_loyalty, name='get_history_client_loyalty'),
    path("loyalty/resolve/", views.resolve_loyalty, name="resolve_loyalty"),
    path("product/", views.view_saleproduct, name='view_saleproduct'),
    path("product/<int:product_id>/get/", views.get_saleproduct, name='get_saleproduct'),
    path("product/<int:product_id>/delete/", views.delete_saleproduct, name='delete_saleproduct'),
    path("recipes/pos/", views.view_sale_recipes, name="view_sale_recipes"),
    path("recipes/pos/<int:product_id>/", views.edit_sale_recipe, name="edit_sale_recipe"),
    path("inventory/", views.view_rawmaterial, name='view_rawmaterial'),
    path("inventory/<int:inventory_id>/get/", views.get_rawmaterial, name='get_rawmaterial'),
    path("inventory/<int:inventory_id>/lots/", views.get_rawmaterial_lots, name='get_rawmaterial_lots'),
    path("inventory/<int:inventory_id>/delete/", views.delete_rawmaterial, name='delete_rawmaterial'),
    path("production/pos/", views.view_sale_production, name="view_sale_production"),
    path("production/report/", views.view_production_report, name="view_production_report"),
    path("pos/", views.view_pos, name='view_pos'),
    path("pos/transaction/add/", views.add_transaction, name='add_transaction'),
    path("pos/shift/start/", views.pos_shift_start, name="pos_shift_start"),
    path("pos/shift/select/", views.pos_shift_select, name="pos_shift_select"),
    path("pos/stock/receive/", views.pos_resale_stock_receive, name="pos_resale_stock_receive"),
    path("pos/stock/receive-ar/", views.pos_ar_stock_receive, name="pos_ar_stock_receive"),
    path("pos/shift/abimes/", views.pos_shift_abimes, name="pos_shift_abimes"),
    path("pos/shift/consumptions/", views.pos_shift_consumptions, name="pos_shift_consumptions"),
    path("pos/shift/expenses/", views.pos_shift_expenses, name="pos_shift_expenses"),
    path("pos/shift/report/", views.pos_shift_report_data, name="pos_shift_report_data"),
    path("pos/shift/cashiers/", views.pos_shift_cashiers, name="pos_shift_cashiers"),
    path("bakery/orders/pending-count/", views.bakery_orders_pending_count, name="bakery_orders_pending_count"),
    path("pos/voucher/scan/", views.pos_voucher_scan, name="pos_voucher_scan"),
    path("pos/voucher/print/", views.print_change_voucher, name="print_change_voucher"),
    path("pos/ticket/print/", views.print_ticket, name='print_ticket'),
    path("pyromane/", views.view_pyromane, name="view_pyromane"),
    path("pyromane/order/create/", views.pyromane_order_create, name="pyromane_order_create"),
    path("pyromane/order/update/", views.pyromane_order_update, name="pyromane_order_update"),
    path("pyromane/order/logs/", views.pyromane_order_logs, name="pyromane_order_logs"),
    path("pyromane/orders/pending/", views.pyromane_orders_pending, name="pyromane_orders_pending"),
    path("pos/order/", views.view_order, name='view_order'),
    path("pos/order/<int:sale_id>/confirmation/", views.confirmation_pos, name='confirmation_pos'),
    path("bakeryproduct/", views.view_bakeryproduct, name='view_bakeryproduct'),
    path("bakeryproduct/<int:product_id>/get/", views.get_bakeryproduct, name='get_bakeryproduct'),
    path("bakeryproduct/<int:product_id>/delete/", views.delete_bakeryproduct, name='delete_bakeryproduct'),
    path("recipes/bakery/", views.view_bakery_recipes, name="view_bakery_recipes"),
    path("recipes/bakery/<int:product_id>/", views.edit_bakery_recipe, name="edit_bakery_recipe"),
    path("production/bakery/", views.view_bakery_production, name="view_bakery_production"),
    path("bakery/", views.view_bakery, name='view_bakery'),
    path("bakery/order/confirmation/", views.order_confirmation, name='order_confirmation'),
    path("sale/", views.view_sale, name='view_sale'),
    path("vouchers/", views.view_cash_change_vouchers, name="view_cash_change_vouchers"),
    path("sale/bakery/<int:sale_id>/get/", views.get_sale, name='get_sale'),
    path("sale/transaction/<int:transaction_id>/get/", views.get_transaction, name='get_transaction'),
    path("sale/bakery/<int:sale_id>/print/", views.print_bakery, name='print_bakery'),
    path("prep/screen/", views.prep_screen, name='prep_screen'),
    path("prep/orders/count/", views.prep_orders_count, name="prep_orders_count"),
    path("prep/orders/count/today/", views.prep_orders_today, name="prep_orders_today"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
