# Generated by Django 5.1.1 on 2025-11-27 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noyau', '0003_salarie_penalty'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noyau.employer')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noyau.shift')),
            ],
        ),
    ]
