# Generated by Django 5.1.1 on 2025-11-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noyau', '0004_employershift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='salary',
        ),
    ]
