# Generated by Django 5.1.1 on 2025-12-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noyau', '0006_bakery_bakeryproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakeryproduct',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
    ]
