# Generated by Django 5.1.1 on 2025-12-09 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noyau', '0007_bakeryproduct_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BakerySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('client', models.CharField(max_length=255)),
                ('phone', models.CharField(default='', max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(max_length=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noyau.employer')),
            ],
        ),
        migrations.CreateModel(
            name='BakerySaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bakery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noyau.bakerysale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noyau.bakeryproduct')),
            ],
        ),
    ]
