# Generated by Django 5.1.1 on 2025-12-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noyau', '0008_bakerysale_bakerysaleitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
