# Generated by Django 5.1.1 on 2025-12-09 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noyau', '0009_sale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Production',
        ),
    ]
