# Generated by Django 5.1.1 on 2025-12-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noyau', '0010_delete_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakerysale',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
