# Generated by Django 5.1.1 on 2025-12-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noyau', '0011_alter_bakerysale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakerysale',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
