# Generated by Django 5.1.1 on 2025-12-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noyau', '0012_alter_bakerysale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakerysale',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
