# Generated by Django 5.1.1 on 2025-12-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noyau', '0013_bakerysale_pickup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakerysale',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
