# Generated by Django 5.1.1 on 2026-03-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noyau', '0014_bakerysale_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='employer',
        ),
        migrations.DeleteModel(
            name='Salarie',
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
