# Generated by Django 5.1.1 on 2026-03-07 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noyau', '0015_remove_leave_employer_delete_salarie_delete_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
                ('assigned_to', models.CharField(max_length=255)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noyau.rawmaterial')),
            ],
        ),
    ]
