# Generated by Django 5.1.1 on 2026-03-07 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noyau', '0016_stockmovement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayoff',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='employershift',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='employershift',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='penalty',
            name='employer',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='DayOff',
        ),
        migrations.DeleteModel(
            name='EmployerShift',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
        migrations.DeleteModel(
            name='Penalty',
        ),
    ]
