# Generated by Django 5.1.1 on 2026-03-07 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noyau', '0017_remove_dayoff_employer_remove_employershift_employer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyalty',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LoyaltyPointLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_type', models.CharField(max_length=20)),
                ('points', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('loyalty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noyau.loyalty')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noyau.saletransaction')),
            ],
        ),
    ]
