# Generated by Django 5.1.1 on 2026-03-07 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noyau', '0018_loyalty_points_loyaltypointledger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyalty',
            name='points',
        ),
    ]
