# Generated by Django 5.1.1 on 2026-03-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noyau', '0019_remove_loyalty_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='saletransaction',
            name='points_earned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='points_redeemed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
