# Generated by Django 5.1.1 on 2026-03-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noyau', '0020_saletransaction_points_earned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyalty',
            name='points_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
