# Generated by Django 5.1.1 on 2026-03-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noyau', '0021_loyalty_points_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltypointledger',
            name='balance_after',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loyaltypointledger',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
