# Generated by Django 5.1.1 on 2026-03-07 19:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noyau', '0022_loyaltypointledger_balance_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saletransaction',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
