# Generated by Django 5.1.1 on 2026-03-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noyau', '0024_recipes_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproduction',
            name='shift',
            field=models.CharField(choices=[('MATIN', 'Matin'), ('SOIR', 'Soir')], default='MATIN', max_length=10),
        ),
    ]
