# Generated by Django 5.1.1 on 2026-03-14 00:00

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noyau', '0025_saleproduction_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosShiftReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField()),
                ('shift', models.CharField(choices=[('MATIN', 'Matin'), ('SOIR', 'Soir')], max_length=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noyau.employer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('shift_date', 'shift'), name='uniq_pos_shift_date')],
            },
        ),
        migrations.CreateModel(
            name='PosShiftAbime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='noyau.saleproduct')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abimes', to='noyau.posshiftreport')),
            ],
        ),
        migrations.CreateModel(
            name='PosShiftConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='noyau.saleproduct')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='noyau.posshiftreport')),
            ],
        ),
        migrations.CreateModel(
            name='PosShiftExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='noyau.posshiftreport')),
            ],
        ),
        migrations.CreateModel(
            name='PosShiftRemise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='noyau.saleproduct')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remises', to='noyau.posshiftreport')),
            ],
        ),
    ]
