# Generated by Django 5.1.1 on 2026-04-03 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noyau', '0035_add_date_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResaleDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noyau.employer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noyau.saleproduct')),
            ],
        ),
    ]
