# Generated by Codex on 2026-04-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noyau", "0036_resaledelivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawmaterial",
            name="stock_mode",
            field=models.CharField(
                choices=[("NORMAL", "Normal"), ("FEFO", "FEFO (expiration)")],
                default="NORMAL",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="RawMaterialLot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("expiration_date", models.DateField(blank=True, db_index=True, null=True)),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("raw_material", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lots", to="noyau.rawmaterial")),
            ],
        ),
    ]

