# Generated by Codex on 2026-04-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noyau", "0037_rawmaterial_fefo"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawmaterial",
            name="linked_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_raw_materials",
                to="noyau.saleproduct",
            ),
        ),
    ]

